apiVersion: v1
kind: Service
metadata:
  name: story-service
spec: # deployment에 의해 생성된 포트 선택
  selector: # story 값이 포함된 app label
    app: story
  type: LoadBalancer
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 3000